sudo: required
dist: bionic

addons:
  apt:
    sources:
      - chef-current-bionic
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - trunk
    - master

services: docker

env:
  - CHEF_LICENSE=accept
  - INSTANCE=resources-ubuntu-1804
  - INSTANCE=resources-ubuntu-2004
  - KITCHEN_YAML=.kitchen.dokken.yml

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}
