name 'chef-steamcmd'
maintainer 'Nick Gray'
maintainer_email 'f0rkz@f0rkznet.net'
license 'Apache-2.0'
description 'Installs steamcmd and steamcmd applications'
version '0.3.1'
chef_version '>= 14'
issues_url 'https://github.com/f0rkz/chef-steamcmd/issues'
source_url 'https://github.com/f0rkz/chef-steamcmd'
depends 'tar'

supports 'ubuntu', '>= 18.04'
